name: ReactNative

# Note: using the `branches` selector excludes all tags
on:
  push:
    branches:
      - '**'

defaults:
  run:
    working-directory: react-native-genius-scan-demo

jobs:
  android:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: 11
    - uses: actions/setup-node@v2
    - run: npm install --force # To solve a conflict with react-native-fs
    - run: cd android && ./gradlew assembleRelease
  ios:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    - run: npm install --force # To solve a conflict with react-native-fs
    - run: cd ios && pod install
    - run: cd ios && xcodebuild archive -workspace demo.xcworkspace -scheme demo CODE_SIGNING_ALLOWED=NO
